import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex flex-row">
          <h1 className="px-2">Root navigation</h1>
          <Link href="about" className="px-2 underline decoration-blue-700">
            About
          </Link>
          <Link href="/" className="px-2 underline decoration-blue-700">
            Home
          </Link>
          <Link href="/users" className="px-2 underline decoration-blue-700">
            Users
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
